# Generated by Django 2.2.13 on 2020-11-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
    ]
