# Generated by Django 2.2.13 on 2020-11-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
